"""Add status column to appointment table

Revision ID: e1466fb35535
Revises: 
Create Date: 2025-03-23 23:45:15.016918

"""
from alembic import op
import sqlalchemy as sa
# Removing MySQL import as we're switching to SQLite
# from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1466fb35535'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('stylist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('specialization',
               existing_type=sa.String(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=20),
               type_=sa.String(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stylist', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=100),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('specialization',
               existing_type=sa.String(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('instagram')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('experience_years')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('category')
        batch_op.drop_column('image_file')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
